---
title: "Muusoctopus Tank Activity"
author: "Cheyne Springbett"
date: "`r Sys.Date()`"
output: html_document
---


```{r}
library(remotes)
install_github("KirtOnthank/CircularTimeHistogram")
library(CircularTimeHistogram)
library(googlesheets4)
library(maptools)
library(png)
```


```{r}
activity=read_sheet("1ckVjS4Jw9o_eg_l_TAwDFNp_evuu36sFHmXyUqT6YqA", sheet="Tank Burrows")
```

```{r}
activity$time=gsub("\\d{5}__TE_D(\\d{4})(\\d{2})(\\d{2})_T(\\d{2})(\\d{2})(\\d{2}).*","\\1-\\2-\\3 \\4:\\5:\\6", activity$`File Name`)

activity$realtime=strptime(activity$time,"%Y-%m-%d %H:%M:%S")

activity$realtime[2]-activity$realtime[1]

```


# 
```{r}
unique(activity$Behavior)
```



```{r}
DayHist(activity$realtime[activity$Behavior=="Entering Burrow"],date="07/31/2022",hist.zoom=4.9,
        hist.col="darkgrey",
        night.col="#C59998",
        day.col="#98C599")
```

```{r}
DayHist(activity$realtime[activity$Behavior=="Exiting Burrow"],date="07/31/2022",hist.zoom=4)
```


```{r}
DayHist(activity$realtime,date="07/31/2022",hist.zoom=12)
```


```{r}
DayHist(activity$realtime[activity$Octopus_Tank!="Amanda_CS2"&
                            activity$Octopus_Tank!="Joe_CS1"&
                            activity$Octopus_Tank!="Naddlie_CS1"&
                            activity$Octopus_Tank!="Rian_CS5"],
        date="07/31/2022",
        hist.zoom=10)
```


```{r}
DayHist(activity$realtime[activity$Octopus_Tank=="Amanda_CS2"|activity$Octopus_Tank=="Joe_CS1"|activity$Octopus_Tank=="Naddlie_CS1"|activity$Octopus_Tank=="Rian_CS5"],
        date="07/31/2022",
        hist.zoom=10)
```